version: '3.8'
services:
  node_backend:
    container_name: node_tabnine
    image: harksahu/eblapi:tag
    build:
      context: .
    depends_on:
      - viasocket_db
    links:
      - viasocket_db
    ports:
      - "7070:7070"
  viasocket_db:
    container_name: viasocket_db
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: viasocket
    